name: Criar Pull Request nos repositórios WL

on:
  push:
    branches:
      - "main"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request on repository-01
        uses: Fitbank-Pagamentos-Eletronicos/osb-action-create-pull-request@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          whiteLabel_source_folder: "*"
          whiteLabel_repo: "Fit-jhameson-farias/repository-01"
          whiteLabel_head_branch: "features"
          user_email_fitbank: "jhameson.farias@fitbank.com.br"
          user_name_fitbank: "Fit-jhameson-farias"

      - name: Create pull request on repository-02
        uses: Fitbank-Pagamentos-Eletronicos/osb-action-create-pull-request@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          whiteLabel_source_folder: "*"
          whiteLabel_repo: "Fit-jhameson-farias/repository-02"
          whiteLabel_head_branch: "features"
          user_email_fitbank: "jhameson.farias@fitbank.com.br"
          user_name_fitbank: "Fit-jhameson-farias"
